"""empty message

Revision ID: 17d2c52b805e
Revises: 
Create Date: 2018-04-08 22:41:06.687213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d2c52b805e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('character_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('character_owner_hash', sa.String(length=255), nullable=True),
    sa.Column('character_name', sa.String(length=200), nullable=True),
    sa.Column('access_token', sa.String(length=100), nullable=True),
    sa.Column('access_token_expires', sa.DateTime(), nullable=True),
    sa.Column('refresh_token', sa.String(length=100), nullable=True),
    sa.Column('latest_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_table('mining_data',
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('solar_system_id', sa.BigInteger(), nullable=False),
    sa.Column('type_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], [u'user.character_id'], ),
    sa.PrimaryKeyConstraint('character_id', 'date', 'solar_system_id', 'type_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mining_data')
    op.drop_table('user')
    # ### end Alembic commands ###
